name: manaweave
description: "Unleash your inner planeswalker with this Commander deck-builder app, featuring a sleek, card-centric UI, intelligent autofill, and a delightful bulk card scanning experience to help you conquer the multiverse!"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  firebase_core: ^3.1.1
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
